# Generated by Django 5.2.4 on 2025-07-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('anons', models.CharField(max_length=50)),
                ('text', models.CharField()),
            ],
        ),
    ]
