# Generated by Django 5.2.4 on 2025-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
